import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-5 flex gap-5`}>
        <div className="w-[454px] h-full">
          {/*Place holder for navbar*/}
        </div>
        {children}
      </body>
    </html>
  );
}
